### ISSUE TITLE
Player control

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-videoball#2]
- [ ] ~keyboard~ (removed for performance issues)
- [x] gamepad

**Comment by mpizenberg** [comment]
Player 1 shooting on spacebar in bb0b8646

**Comment by Soreine** [comment]
Gamepad support will probably become mandatory for local play. Because of keyboard ghosting, it's not conceivable to have more than 2 people using one keyboard at a time.

> “Ghosting” is the problem that some keyboard keys don’t work when multiple keys are pressed simultaneously.

I have never used gamepads in JS, but hey...
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

**Comment by mpizenberg** [comment]
For gamepad in elm: https://github.com/xarvh/elm-gamepad

**Comment by mpizenberg** [comment]
It mostly works but there are still two issues:
- Does not work in Firefox, only in Chrome (should not be the case, maybe an elm-gamepad issue)
- 4th controller is not detected in browser, no idea why.
